-- Auto-generated by a read-only diff of Railway production DB vs local DB
-- Generated: 2026-07-13T16:29:34.114Z

-- This file ONLY contains INSERT statements for rows that exist on Railway
-- but were not found (by primary key) in the local database.
-- Review before running. Wrapped in a transaction so it is all-or-nothing.
-- ON CONFLICT (pk) DO NOTHING makes re-running this file safe (idempotent).

BEGIN;
-- capital_investments: 5 row(s) present on Railway but not found locally
INSERT INTO "capital_investments" ("id", "amount", "category", "note", "invested_at", "created_by", "created_at", "payroll_record_id") VALUES ('1526eed7-c1a6-4de4-aebf-436439e60d28', '1600.00', 'equipment', 'Extra keys', '2026-07-08T18:30:00.000Z', '1780832c-72e5-4772-b693-4f7df4ac8f05', '2026-07-09T10:27:52.238Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "capital_investments" ("id", "amount", "category", "note", "invested_at", "created_by", "created_at", "payroll_record_id") VALUES ('645a7975-a615-4caa-985e-ed6be6e21b1d', '380.00', 'equipment', 'QR Card', '2026-07-05T18:30:00.000Z', '1780832c-72e5-4772-b693-4f7df4ac8f05', '2026-07-09T03:49:34.176Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "capital_investments" ("id", "amount", "category", "note", "invested_at", "created_by", "created_at", "payroll_record_id") VALUES ('910e17a5-b79b-4860-9d3d-ca9da643a63b', '22000.00', 'other', 'Social media (june)', '2026-07-11T18:30:00.000Z', '1780832c-72e5-4772-b693-4f7df4ac8f05', '2026-07-13T04:17:19.786Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "capital_investments" ("id", "amount", "category", "note", "invested_at", "created_by", "created_at", "payroll_record_id") VALUES ('ba72545a-051b-4026-8a98-b085ce4aa33a', '63000.00', 'equipment', 'Shoe rack, belt rack, table (Balance)', '2026-07-07T18:30:00.000Z', '1780832c-72e5-4772-b693-4f7df4ac8f05', '2026-07-09T03:48:10.849Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "capital_investments" ("id", "amount", "category", "note", "invested_at", "created_by", "created_at", "payroll_record_id") VALUES ('f4892ac3-65fd-4aab-b35a-83cfd9c03411', '50000.00', 'equipment', 'Shoe rack, belt rack, table (Advance)', '2026-07-05T18:30:00.000Z', '1780832c-72e5-4772-b693-4f7df4ac8f05', '2026-07-09T03:47:25.781Z', NULL) ON CONFLICT ("id") DO NOTHING;

-- cash_sessions: 10 row(s) present on Railway but not found locally
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('1c437f7d-9c74-432d-b353-43ae06c2c9df', '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '3379.00', '3379.00', NULL, 'closed', '2026-07-10T12:31:24.101Z', '2026-07-10T13:32:32.073Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('29bd1850-09f1-4bb8-b5cc-651198e58b88', '30f4475f-a234-4cb8-908f-9fd67011cd96', '3379.00', '3379.00', NULL, 'closed', '2026-07-10T03:53:14.914Z', '2026-07-10T12:30:57.222Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('4edd5aed-be8f-4730-9c6b-85b9cc6704f7', '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '3379.00', '3379.00', NULL, 'closed', '2026-07-11T03:30:37.330Z', '2026-07-11T12:38:26.467Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('825829b0-aa06-4be3-af08-637d2c0ae177', '30f4475f-a234-4cb8-908f-9fd67011cd96', '3379.00', '3379.00', NULL, 'closed', '2026-07-11T12:38:50.405Z', '2026-07-11T13:35:20.889Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('bb6fe5a5-5ba5-4d51-a98f-4b5d6f709e0f', '30f4475f-a234-4cb8-908f-9fd67011cd96', '3379.00', '3379.00', NULL, 'closed', '2026-07-08T03:39:27.180Z', '2026-07-08T13:30:39.662Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('bd534172-2737-4adb-83ca-075d60d15e5a', '30f4475f-a234-4cb8-908f-9fd67011cd96', '3379.00', '3379.00', NULL, 'closed', '2026-07-09T08:03:35.375Z', '2026-07-09T12:28:41.887Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('c2472601-60f0-4431-8b0f-075552bf5ab3', '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '3379.00', '3379.00', NULL, 'closed', '2026-07-09T03:31:11.881Z', '2026-07-09T08:02:55.227Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('c6864421-143e-45c5-97a6-fc7208e40d34', '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '3379.00', '3379.00', NULL, 'closed', '2026-07-13T03:25:05.198Z', '2026-07-13T12:34:24.125Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('cd82c026-fae7-407f-bb1f-8e890a73a5cc', '30f4475f-a234-4cb8-908f-9fd67011cd96', '3379.00', '3379.00', NULL, 'closed', '2026-07-12T02:57:16.466Z', '2026-07-12T12:35:32.128Z', '0.00') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "cash_sessions" ("id", "user_id", "opening_balance", "closing_balance", "notes", "status", "opened_at", "closed_at", "cashout_amount") VALUES ('d0c630a7-cb93-4f03-8dfe-383e7a94abf7', '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '3379.00', '3379.00', NULL, 'closed', '2026-07-12T12:40:41.952Z', '2026-07-12T13:33:38.918Z', '0.00') ON CONFLICT ("id") DO NOTHING;

-- customers: 1 row(s) present on Railway but not found locally
INSERT INTO "customers" ("id", "name", "phone", "whatsapp", "email", "address", "notes", "created_at", "updated_at") VALUES ('ca956557-fbe1-4228-8984-569f4bce9c04', 'Kaveesha Gangadhara', '0775258429', '0775258429', NULL, NULL, NULL, '2026-07-11T13:14:43.041Z', '2026-07-11T13:14:43.041Z') ON CONFLICT ("id") DO NOTHING;

-- rentals: 1 row(s) present on Railway but not found locally
INSERT INTO "rentals" ("id", "booking_number", "customer_id", "status", "rental_start_date", "rental_end_date", "actual_return_date", "advance_payment", "total_rental_cost", "total_fine", "discount_amount", "notes", "event_type", "created_by", "created_at", "updated_at", "security_type", "security_deposit", "security_id_number", "event_date") VALUES ('726ce4bd-7641-4db3-8458-2bb410ca1b35', 'TS-2026-0023', 'ca956557-fbe1-4228-8984-569f4bce9c04', 'picked_up', '2026-07-10T18:30:00.000Z', '2026-07-12T18:30:00.000Z', NULL, '2200.00', '2200.00', '0.00', '0.00', '', NULL, '30f4475f-a234-4cb8-908f-9fd67011cd96', '2026-07-11T13:24:41.206Z', '2026-07-11T13:25:36.281Z', NULL, '0.00', NULL, '2026-07-11T18:30:00.000Z') ON CONFLICT ("id") DO NOTHING;

-- product_variants: 1 row(s) present on Railway but not found locally
INSERT INTO "product_variants" ("id", "product_id", "sku", "size", "color", "material", "selling_price", "rental_price_per_day", "stock_quantity", "available_for_rent", "damaged_count", "created_at", "updated_at", "label_id") VALUES ('81824a2b-868e-4f5b-9593-f7b7862dc6d5', '7a65c95c-161a-467b-9115-324ef7e0cf9e', 'TS-B-LIGH-53VC-58-LIG-R', '58', 'Light Grey 1-R', NULL, '25000.00', '1500.00', 0, 0, 0, '2026-07-11T13:09:01.615Z', '2026-07-11T13:24:41.206Z', 313) ON CONFLICT ("id") DO NOTHING;

-- inventory_movements: 5 row(s) present on Railway but not found locally
INSERT INTO "inventory_movements" ("id", "product_variant_id", "type", "quantity", "reason", "reference_id", "reference_type", "created_by", "created_at") VALUES ('1d112c56-ca44-42d2-bd46-b8d3a53d7a66', '81824a2b-868e-4f5b-9593-f7b7862dc6d5', 'rental_out', 1, 'Rental booking', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'rental', '30f4475f-a234-4cb8-908f-9fd67011cd96', '2026-07-11T13:24:41.206Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "inventory_movements" ("id", "product_variant_id", "type", "quantity", "reason", "reference_id", "reference_type", "created_by", "created_at") VALUES ('5de6e1aa-a1d8-4d19-a668-6193ebf3878b', 'dc5a4dc9-2b2b-4cfb-91d6-d3b437bb6c51', 'rental_out', 1, 'Rental booking', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'rental', '30f4475f-a234-4cb8-908f-9fd67011cd96', '2026-07-11T13:24:41.206Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "inventory_movements" ("id", "product_variant_id", "type", "quantity", "reason", "reference_id", "reference_type", "created_by", "created_at") VALUES ('bf053da8-1601-42e1-8701-58c1e00876f2', '81824a2b-868e-4f5b-9593-f7b7862dc6d5', 'in', 1, 'Transferred from sale pool', NULL, NULL, '30f4475f-a234-4cb8-908f-9fd67011cd96', '2026-07-11T13:09:01.615Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "inventory_movements" ("id", "product_variant_id", "type", "quantity", "reason", "reference_id", "reference_type", "created_by", "created_at") VALUES ('e9c7bc6b-4b75-4676-a909-1df75def8f76', '5f558b4c-b449-48a5-8804-1363306bf2fa', 'out', 1, 'POS Sale', '51e41b8d-9cfd-42aa-8f2e-4b10d51d4915', 'sale', '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '2026-07-11T03:45:49.452Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "inventory_movements" ("id", "product_variant_id", "type", "quantity", "reason", "reference_id", "reference_type", "created_by", "created_at") VALUES ('eaa76877-c540-4a89-9667-c26edffcf4b7', '80e33ff5-9a6d-44d9-9006-97321787a589', 'out', 1, 'Transferred to rental pool', NULL, NULL, '30f4475f-a234-4cb8-908f-9fd67011cd96', '2026-07-11T13:09:01.615Z') ON CONFLICT ("id") DO NOTHING;

-- notification_logs: 6 row(s) present on Railway but not found locally
INSERT INTO "notification_logs" ("id", "rental_id", "customer_id", "type", "channel", "recipient", "message", "status", "error_message", "sent_at", "created_at") VALUES ('2be114ab-a4d1-4990-a7c0-c88dd3c72010', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'ca956557-fbe1-4228-8984-569f4bce9c04', 'picked_up', 'whatsapp', '0775258429', 'Dear Kaveesha Gangadhara,

Your rental items (#TS-2026-0023) have been picked up successfully.

Please return them by: 13 July 2026

Thank you for choosing The Outfit Lounge!', 'sent', NULL, '2026-07-11T13:25:52.347Z', '2026-07-11T13:25:36.320Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "notification_logs" ("id", "rental_id", "customer_id", "type", "channel", "recipient", "message", "status", "error_message", "sent_at", "created_at") VALUES ('6633cf66-8cd4-419d-ad4f-3d5e4a14c7fe', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'ca956557-fbe1-4228-8984-569f4bce9c04', 'return_reminder', 'whatsapp', '0775258429', 'Dear Kaveesha Gangadhara,
This is a friendly reminder to return your rented items for booking #TS-2026-0023.

📅 Return Date: 2026-07-13
🏪 Please return before 5:30 PM (shop closing time).

Kindly ensure items are returned on time to avoid late charges.
Thank you,
THE OUTFIT LOUNGE', 'sent', NULL, '2026-07-12T09:00:00.969Z', '2026-07-12T09:00:00.795Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "notification_logs" ("id", "rental_id", "customer_id", "type", "channel", "recipient", "message", "status", "error_message", "sent_at", "created_at") VALUES ('6bc6adcf-bd78-49e0-b652-0a7465679378', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'ca956557-fbe1-4228-8984-569f4bce9c04', 'booking_confirmed', 'whatsapp', '0775258429', 'Dear Kaveesha Gangadhara,
Your full suit rental booking #TS-2026-0023 has been successfully confirmed.

📅 Pickup Date: 11 July 2026
🎉 Event Date: 12 July 2026
📅 Return Date: 13 July 2026
💰 Total Amount: LKR 2200.00
✅ Fully Paid: LKR 2200.00

Thank you for choosing THE OUTFIT LOUNGE
We look forward to serving you.', 'sent', NULL, '2026-07-11T13:24:41.497Z', '2026-07-11T13:24:41.286Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "notification_logs" ("id", "rental_id", "customer_id", "type", "channel", "recipient", "message", "status", "error_message", "sent_at", "created_at") VALUES ('77e441ba-7069-4afe-8e72-f8130c77d636', NULL, 'c206bba3-a2ee-4d6a-87d0-b17147ab83cb', 'pos_invoice', 'sms', '0740245964', 'Dear Rukshan,

Thank you for shopping with The Outfit Lounge.

Your purchase has been completed successfully.

🧾 Invoice No: SALE-202607-0004
💰 Total Amount: LKR 2,541.50
💳 Payment Method: Card
📅 Date: 11 Jul 2026

We truly appreciate your business and look forward to serving you again.

Thank you,
THE OUTFIT LOUNGE', 'sent', NULL, '2026-07-11T03:45:52.249Z', '2026-07-11T03:45:52.075Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "notification_logs" ("id", "rental_id", "customer_id", "type", "channel", "recipient", "message", "status", "error_message", "sent_at", "created_at") VALUES ('9e76f1b8-4e4f-4ecb-9a0e-5f414000dd83', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'ca956557-fbe1-4228-8984-569f4bce9c04', 'return_reminder', 'whatsapp', '0775258429', 'Dear Kaveesha Gangadhara,
This is a friendly reminder to return your rented items for booking #TS-2026-0023.

📅 Return Date: 13 July 2026
🏪 Please return before 5:30 PM (shop closing time).

Kindly ensure items are returned on time to avoid late charges.
Thank you,
THE OUTFIT LOUNGE', 'sent', NULL, '2026-07-13T03:49:40.618Z', '2026-07-13T03:49:40.457Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "notification_logs" ("id", "rental_id", "customer_id", "type", "channel", "recipient", "message", "status", "error_message", "sent_at", "created_at") VALUES ('da3422cd-f0a5-453a-923e-b4ccf53accf6', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'ca956557-fbe1-4228-8984-569f4bce9c04', 'ready_for_pickup', 'whatsapp', '0775258429', 'Dear Kaveesha Gangadhara,
Your full suit rental booking #TS-2026-0023 is now ready for pickup.

🕒 Pickup Date & Time: 11 July 2026
📅 Return Date: 13 July 2026
✅ Fully Paid

Please visit THE OUTFIT LOUNGE at your convenience.
Thank you for choosing us.', 'sent', NULL, '2026-07-11T13:24:45.959Z', '2026-07-11T13:24:45.821Z') ON CONFLICT ("id") DO NOTHING;

-- sales: 1 row(s) present on Railway but not found locally
INSERT INTO "sales" ("id", "sale_number", "customer_id", "subtotal", "discount_amount", "tax_amount", "total_amount", "amount_paid", "change_amount", "payment_method", "status", "notes", "created_by", "created_at", "invoice_pdf_path") VALUES ('51e41b8d-9cfd-42aa-8f2e-4b10d51d4915', 'SALE-202607-0004', 'c206bba3-a2ee-4d6a-87d0-b17147ab83cb', '2990.00', '448.50', '0.00', '2541.50', '2541.50', '0.00', 'card', 'completed', NULL, '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '2026-07-11T03:45:49.452Z', 'invoices/Receipt_SALE-202607-0004.pdf') ON CONFLICT ("id") DO NOTHING;

-- payments: 2 row(s) present on Railway but not found locally
INSERT INTO "payments" ("id", "rental_id", "sale_id", "amount", "payment_method", "payment_type", "notes", "created_by", "created_at") VALUES ('e02beae0-1980-4e5d-9e87-2d67114541b6', NULL, '51e41b8d-9cfd-42aa-8f2e-4b10d51d4915', '2541.50', 'card', 'full', NULL, '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '2026-07-11T03:45:49.452Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO "payments" ("id", "rental_id", "sale_id", "amount", "payment_method", "payment_type", "notes", "created_by", "created_at") VALUES ('e483c084-b361-4f4a-9fb8-07d57d8236d6', '726ce4bd-7641-4db3-8458-2bb410ca1b35', NULL, '2200.00', 'card', 'full_payment', NULL, '30f4475f-a234-4cb8-908f-9fd67011cd96', '2026-07-11T13:24:41.206Z') ON CONFLICT ("id") DO NOTHING;

-- promotion_code_usages: 1 row(s) present on Railway but not found locally
INSERT INTO "promotion_code_usages" ("id", "promotion_code_id", "sale_id", "rental_id", "discount_amount", "used_by", "used_at") VALUES ('40053a85-953f-431d-be31-60f5fc26e67a', 'd75d6f10-f76d-4e72-a456-c5b23749f806', '51e41b8d-9cfd-42aa-8f2e-4b10d51d4915', NULL, '448.50', '6ff914ce-d228-4c66-b8f1-e9a04d78e706', '2026-07-11T03:45:49.452Z') ON CONFLICT ("id") DO NOTHING;

-- rental_items: 2 row(s) present on Railway but not found locally
INSERT INTO "rental_items" ("id", "rental_id", "product_variant_id", "quantity", "rental_price_per_day", "is_returned", "return_condition", "returned_at", "created_at", "damage_remark") VALUES ('1e8809f8-94f5-47a1-949f-45f8ff73f189', '726ce4bd-7641-4db3-8458-2bb410ca1b35', 'dc5a4dc9-2b2b-4cfb-91d6-d3b437bb6c51', 1, '700.00', FALSE, NULL, NULL, '2026-07-11T13:24:41.206Z', NULL) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "rental_items" ("id", "rental_id", "product_variant_id", "quantity", "rental_price_per_day", "is_returned", "return_condition", "returned_at", "created_at", "damage_remark") VALUES ('38bb461b-00d2-4e4f-a438-28b740bc2260', '726ce4bd-7641-4db3-8458-2bb410ca1b35', '81824a2b-868e-4f5b-9593-f7b7862dc6d5', 1, '1500.00', FALSE, NULL, NULL, '2026-07-11T13:24:41.206Z', NULL) ON CONFLICT ("id") DO NOTHING;

-- sale_items: 1 row(s) present on Railway but not found locally
INSERT INTO "sale_items" ("id", "sale_id", "product_variant_id", "product_name", "variant_info", "quantity", "unit_price", "discount", "subtotal") VALUES ('b7100edb-b63c-4ebb-91c5-898407857fff', '51e41b8d-9cfd-42aa-8f2e-4b10d51d4915', '5f558b4c-b449-48a5-8804-1363306bf2fa', 'AZZARO WANTED BY NIGHT EDP', '5ML', 1, '2990.00', '0.00', '2990.00') ON CONFLICT ("id") DO NOTHING;


COMMIT;
